### ISSUE TITLE
appveyor: consider using just a .bat script

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1809]
See how libmypaint does it https://github.com/mypaint/libmypaint/blob/master/appveyor.bat

**Comment by bassosimone** [comment]
Something like the following should in principle work:

```yaml
image: Visual Studio 2017

environment:
  matrix:
    - PATH: "C:/msys64/x86_64/bin;C:/msys64/usr/bin"
      HOME: C:/projects/measurement-kit

before_build:
  - cmd: bash -lc "pacman --noconfirm -Syy pacman"
  - cmd: bash -lc "pacman --noconfirm -Syyuu"
  - cmd: bash -lc "pacman --noconfirm -S --needed base-devel"
  - cmd: bash -lc "pacman --noconfirm -S --needed mingw-w64-x86_64-toolchain"
  - cmd: bash -lc "pacman --noconfirm -S --needed libreadline"

build_script:
  - cmd: bash -lc "./autogen.sh"
  - cmd: bash -lc "./configure --disable-dependency-tracking --with-ca-bundle=cacert.pem"
  - cmd: bash -lc "make -j`nproc` check TESTS="

test_script:
  - cmd: bash -lc "make -j8 check"

on_failure:
  - cmd: bash -lc "cat ./test-suite.log"
```
